### PR TITLE
Tiny bits

### PR DESCRIPTION
**Pull request by nulltoken**
:hash: :one: :bangbang: 
- A better cross_platform contributing experience
- Missing trailing newlines make Linus cries. You do not want to do cause this
- Continuous integration rocks! Let's make this happen

### CODE REVIEW

**Comment by nulltoken** [comment]
Well Travis **[seems to be working](https://travis-ci.org/nulltoken/tar-cs-lb2s/jobs/3961405)**. All you have to do is to sign in and activate the GitHub service Hook as described in the **[documentation](http://about.travis-ci.org/docs/user/getting-started/)** in order to enroll the yorah/tar-cs-lb2s repository.

One issue though. I'm not sure if this is related to the test helper infrastructure or the way the way format is implemented (Shouldn't a tar generated on a Windows platform be understood by a Linux one?).

I'd definitively prefer you to take a look.

```
/home/travis/builds/nulltoken/tar-cs-lb2s/CI-build.msbuild: error : tar_cs.Tests.TarWriterFixture.CanCreateATarFileWithMultipleFileEntriesWithADeepHierarchy: Assert.Equal() Failure
Position: First difference is at position 4
Expected: deep\1.txt00007770000000000000000000000053013648147780011456 ustar00rootrootThe quick brown fox jumps over the lazy dogdeep\2\fox.txt00007770000000000000000000000053013648147780012330 ustar00rootrootThe quick brown fox jumps over the lazy dogdeep\2\3\dog.txt00007770000000000000000000000014013648147780012521 ustar00rootrootnobody jumps
Actual:   deep/1.txt00007770000000000000000000000053013648219780011401 ustar00rootrootThe quick brown fox jumps over the lazy dogdeep/2/fox.txt00007770000000000000000000000053013648219780012176 ustar00rootrootThe quick brown fox jumps over the lazy dogdeep/2/3/dog.txt00007770000000000000000000000014013648219780012312 ustar00rootrootnobody jumps
    /home/travis/builds/nulltoken/tar-cs-lb2s/CI-build.msbuild: error :   at tar_cs.Tests.TarWriterFixture.CanCreateATarFileWithMultipleFileEntriesWithADeepHierarchy () [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
    /home/travis/builds/nulltoken/tar-cs-lb2s/CI-build.msbuild: error : tar_cs.Tests.TarWriterFixture.CanCreateATarFileWithMultipleFileEntries: Assert.Equal() Failure
Position: First difference is at position 8
Expected: multiple\1.txt00007770000000000000000000000053013648147780012374 ustar00rootrootThe quick brown fox jumps over the lazy dogmultiple\2.txt00007770000000000000000000000053013648147780012375 ustar00rootrootThe quick brown dog jumps over the lazy fox
Actual:   multiple/1.txt00007770000000000000000000000053013648219780012317 ustar00rootrootThe quick brown fox jumps over the lazy dogmultiple/2.txt00007770000000000000000000000053013648219780012320 ustar00rootrootThe quick brown dog jumps over the lazy fox
    /home/travis/builds/nulltoken/tar-cs-lb2s/CI-build.msbuild: error :   at tar_cs.Tests.TarWriterFixture.CanCreateATarFileWithMultipleFileEntries () [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
    /home/travis/builds/nulltoken/tar-cs-lb2s/CI-build.msbuild: error : tar_cs.Tests.TarWriterFixture.CanCreateATarFileWithOneFileEntry: Assert.Equal() Failure
Position: First difference is at position 6
Expected: single\1.txt00007770000000000000000000000053013648147780012022 ustar00rootrootThe quick brown fox jumps over the lazy dog
Actual:   single/1.txt00007770000000000000000000000053013648219780011745 ustar00rootrootThe quick brown fox jumps over the lazy dog
    /home/travis/builds/nulltoken/tar-cs-lb2s/CI-build.msbuild: error :   at tar_cs.Tests.TarWriterFixture.CanCreateATarFileWithOneFileEntry () [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
```

**Comment by yorah** [comment]
Nice!

The problem is in the test infrastructure. I'm comparing the generated tar (actual) with a previously-generated one (expected) which I store in .\Resources\results. As the expected one has been generated on windows, it contains '\' instead of '/'.

I think it should be ok to always use forward slashes, even on windows, and that way we will generate the same tar on windows and on mono.

I'll take care of it, and add the hook to Travis. Thanks a lot! :love_hotel:

**Comment by nulltoken** [comment]
I've made some tests and generated some tar files on Windows by using 7zip.

```
D:\tar-cs-lb2s\tar-cs.Tests\Resources>"C:\Program Files\7-Zip\7z.exe" a -ttar test.tar single\1.txt
```

Even if the passed filepath contains a backslash, the generated tar contains a forward slash. This can be verified with a hex editor.

From a testing perspective, maybe would it be wise to generate the tar files using an external program and store the resulting archives in `result`. This way we would test that tar-cs generates something which matches a verified output produced by a trusted tar program, not by tar-cs itself.

**Comment by yorah** [comment]
I thought about generating the result tar files with an external program, but as we hardcode the value of `userId`, `groupId`, `userName` and `groupId` (in the constructor of `UsTarHeader`), this wouldn't work.

Why do we hardcode those values? Well, because it's what git.git does in [archive-tar.c](https://github.com/git/git/blob/master/archive-tar.c#L172-L177). It means that currently, tar-cs-lb2s is just a trimmed down version of tar-cs. which only makes sense in the context of LibGit2Sharp.

Let's go back in time. I created this repo to be able to test tar-cs for libgit2/libgit2sharp#246, and at the same abstracting myself from libgit2sharp. However, as the end-result of all this is a single `TarWriter` file, which has almost the same kind of responsability than git.git `archive-tar.c`, maybe it would make more sense to incorporate it back into libgit2sharp?

**Remark about the tests**: the results files have been generated with tar-cs, but I've checked them both manually (with an hex editor... it was kind of painful as you can imagine :wink:), and with external programs (izarc and 7zip), to make sure they end up being valid tar files. As it stands, they are just used as glorified non-regression tests.

**Comment by nulltoken** [comment]
> I thought about generating the result tar files with an external program, but as we hardcode the value of `userId`, `groupId`, `userName` and `groupId` (in the constructor of `UsTarHeader`), this wouldn't work.

Oh. I haven't noticed this. Indeed, my proposal makes no sense considering this.

> However, as the end-result of all this is a single `TarWriter` file, which has almost the same kind of responsability than git.git archive-tar.c, maybe it would make more sense to incorporate it back into libgit2sharp?

Yes, I think this is a reasonable option ;-). However, I'd like the `tar-cs-lb2s` to live its separate life. This is the place where we should fix bugs and run tests. We would only upgrade the `TarWriter` file in the LibGit2Sharp repository whenever that's needed.

> I've checked them (the results files) [...] with external programs (izarc and 7zip) to make sure they end up being valid tar files.

Hmm. That's weird because I can't open any of files in the `results` folder with 7zip. Switching to `GenerateTestFiles` configuration and working with the produced tars doesn't help much for files with entries. However, the generated tar archive with no entry can be successfully opened. Can you reproduce this or is it a local problem to my box?

However, I think you're right, storing paths in the archive with forward slashes would be a valid solution. It looks like **[SharpZipLib](https://github.com/icsharpcode/SharpZipLib/wiki/GZip-and-Tar-Samples)** relies on the same trick.

**Comment by nulltoken** [comment]
> > I thought about generating the result tar files with an external program, but as we hardcode the value of `userId`, `groupId`, `userName` and `groupId` (in the constructor of `UsTarHeader`), this wouldn't work.

Giving a little more thinking about this, I may have another proposal. As I do not know all the gory details about the archive format, please bear with me :stuck_out_tongue_winking_eye:. As Git hardcode these values, why don't we generate the test archive through Git? This way, we would test against a trusted file format, wouldn't we?

**Comment by nulltoken** [comment]
> As Git hardcode these values, why don't we generate the test archive through Git? This way, we would test against a trusted file format, wouldn't we?

Hmmm. The `pax_global_header` goes in the way for now.

**Pull request closed without merging**
